Update ezcater_docker_shared v1.1.0 and regen scripts (#59)

diff --git a/docker/artifactory_setup b/docker/artifactory_setup
--- a/docker/artifactory_setup
+++ b/docker/artifactory_setup
@@ -1,6 +1,6 @@
-export BUNDLE_EZCATER__JFROG__IO=$(bundle config ezcater.jfrog.io | tail -1 | cut -d\" -f 2)
+export BUNDLE_EZCATER__JFROG__IO=$(grep -e "^BUNDLE_EZCATER__JFROG__IO:" ~/.bundle/config | cut -d\" -f 2)
 if [ -z "$BUNDLE_EZCATER__JFROG__IO" ]; then
   echo "" >&2
-  echo "Command Failed: Ensure that bundler is installed locally and that credentials are configured for ezcater.jfrog.io." >&2
+  echo "Command Failed: Ensure that bundler is configured with credentials for ezcater.jfrog.io." >&2
   exit 1
 fi
